# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('stateMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='join',
            managers=[
                ('joinsMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trips',
            managers=[
                ('tripsMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('registerMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
