# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_auto_20161026_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='unique_id',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
