# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20161028_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
