# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_messages_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comments',
            managers=[
                ('commentMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='messages',
            managers=[
                ('messageMgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='unique_trail_id',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
